### ISSUE TITLE
PHP 7

### ISSUE THREAD

**Issue by dterweij** [elliottb/phpgraphlib#24]
Script does not load on PHP 7. Please make it compatible with PHP 7.

**Comment by cremersdh** [comment]
You can easily correct it yourself
It has to do with the "Redefinition of parameter" which is not allowed in PHP 7 anymore
just edit phpgraphlib.php and correct 2 lines:

line 739
  protected function imagelinedashed(&$image_handle, $x_axis_x1, $yLocation, $x_axis_x2 , $yLocation, $color)
into 
  protected function imagelinedashed(&$image_handle, $x_axis_x1, $yLocation, $x_axis_x2 , $color)

line 775
$this->imagelinedashed($this->image, $this->x_axis_x1, $yLocation, $this->x_axis_x2 , $yLocation, $color);
into 
$this->imagelinedashed($this->image, $this->x_axis_x1, $yLocation, $this->x_axis_x2 , $color);

**Comment by elliottb** [comment]
@cremersdh, @dterweij: thanks! Fix in master: https://github.com/elliottb/phpgraphlib/commit/479ec384e80ee5cda3f081b5715ab6f86982d38d.
