### ISSUE TITLE
Stacked graphs limited to 5 values in array

### ISSUE THREAD

**Issue by adamjmason** [elliottb/phpgraphlib#26]
Having issues with stacked graphs.
Tried adding 8 values to a stack in a stacked bar chart - the graph only picks up the first 5 in the array.
Repeated with 6, same is true. The legend only displays the first 5 values too.

Is this a known limitation?

**Comment by elliottb** [comment]
Can you supply the code you were using for this? Thanks!

**Comment by adamjmason** [comment]
Sorry for prematurely posting - I found the code that controls this and
amended.
My issue was resolved by the following changes:


*phpgraphlib.php:*
*ln-1419-1421:*
public function setBarColor($color1, $color2 = '', $color3 = '', $color4 =
'', $color5 = '', $color6 = '', $color7 = '', $color8 = '')
{
$bar_colors = array($color1, $color2, $color3, $color4, $color5, $color6,
$color7, $color8);

*ln-1449-1451:*
public function setLineColor($color1, $color2 = '', $color3 = '', $color4 =
'', $color5 = '', $color6 = '', $color7 = '', $color8 = '')
{
$line_colors = array($color1, $color2, $color3, $color4, $color5, $color6,
$color7, $color8);

*ln-1528-1530:*
public function setLegendTitle($title1, $title2 = '', $title3 = '', $title4
= '', $title5 = '', $title6 = '', $title7 = '', $title8 = '')
{
$title_array = array($title1, $title2, $title3, $title4, $title5, $title6,
$title7, $title8);


*phpgraphlib_stacked.php:*
*ln-171-173:*
public function addData($data, $data2 = '', $data3 = '', $data4 = '',
$data5 = '', $data6 = '', $data7 = '', $data8 = '')
{
parent::addData($data, $data2, $data3, $data4, $data5, $data6, $data7,
$data8);

**Comment by elliottb** [comment]
Great, thanks @adamjmason. Closing.
