### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by oreiner** [elliottb/phpgraphlib#46]
Hi, the ebrueggeman.com seems to be offline and I don't see that the documentation has been imported to GitHub. :(
Is it anywhere to be found?

I replicated my website and the graphs stopped working on the new server. Seems to be some config issue of the server, but I can't figure out what's missing.

Thanks in Advance. The Library is great, it's a shame the original website is gone!

**Comment by LupenWonse** [comment]
Hi,
Sad to see the webpage go but luckily nothing really is lost on the internet.
Way back machine to the rescue for the original documentation:
[Documentation](https://web.archive.org/web/20180121185935/http://www.ebrueggeman.com/phpgraphlib/documentation)
Btw, my guess is that you are missing the GD2 graph library installation.

**Comment by oreiner** [comment]
Wow great, thanks a lot! I don't know why I wasn't aware of way back machine :P 

GD2 was my (post-google) thought too, but it seems it is indeed installed & enabled on the (shared) server. So no luck there :(

Weirdly enough, I just noticed that using the constructor's optional parameter to output into an image file works fine. i.e. if I write
$graph = new PHPGraphLib(600,400, "image.png"); 
and go to image.png I see the graph, but  
$graph = new PHPGraphLib(600,400); 
and going to the php page just says the image cannot be displayed due to errors, although this works on the other server
Any hint to what's going on?

**Comment by LupenWonse** [comment]
Don’t have access to a computer atm, but check the version of php installed on each server. 

Seems to me like a difference in how php handles the constructor (overwriting).

**Comment by oreiner** [comment]
There was a small difference (7.0 & 7.1) but updating both to 7.3 didn't change the situation. Still works on the old server and doesn't on the new one.

**Comment by LupenWonse** [comment]
This is very strange behavior.
But between php 7.0 and 7.1+ this library was actually broken. Are you using the original phpgraphlib? Did you  implement any fix for 7.1+?
See this issue: #43 
And see this fix #44 

Otherwise looking at your error logs might give some hints.

**Comment by oreiner** [comment]
Yes I'm using the original lib and implementing this fix (plus the fix for 7.3, didn't check it separately) did the trick, thank you so much!

Not sure why upgrading to 7.1/7.3 on the old server didn't break the code, but I'm just glad it works on the new one now.
